general_settings:
  master_key: sk-dummy
litellm_settings:
  drop_params: true
model_list:
- model_name: claude-sonnet-4.5.5
  litellm_params:
    model: github_copilot/claude-sonnet-4.5.5
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"
- model_name: claude-opus-41
  litellm_params:
    model: github_copilot/claude-opus-41
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"
- model_name: gpt-5
  litellm_params:
    model: github_copilot/gpt-5
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"
- model_name: claude-opus-4
  litellm_params:
    model: github_copilot/claude-opus-4
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"
- model_name: claude-sonnet-4.5
  litellm_params:
    model: github_copilot/claude-sonnet-4.5
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"
- model_name: "*" # All other supported models go here (e.g. gpt-5-mini, etc)
  litellm_params:
    model: "github_copilot/*"
    extra_headers:
      editor-version: "vscode/1.104.3"
      editor-plugin-version: "copilot-chat/0.26.7"
      Copilot-Integration-Id: "vscode-chat"
      user-agent: "GitHubCopilotChat/0.26.7"
      x-github-api-version: "2025-04-01"